import os
from datetime import datetime, timedelta
from fpdf import FPDF
from database.db import (
    get_statistics, get_violations_by_type, get_repeat_offenders,
    get_hotspots, get_violations_by_day, save_report,
)
import config


class TrafficReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(30, 64, 175)
        self.cell(0, 10, 'TRINETRA AI - Traffic Enforcement Intelligence Report', align='C', new_x='LMARGIN', new_y='NEXT')
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by TRINETRA AI Platform', align='C')

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(55, 65, 81)
        self.cell(0, 10, title, new_x='LMARGIN', new_y='NEXT')
        self.set_draw_color(30, 64, 175)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def key_value(self, key, value):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(75, 85, 99)
        self.cell(60, 7, key)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(31, 41, 55)
        self.cell(0, 7, str(value), new_x='LMARGIN', new_y='NEXT')

    def write_table(self, headers, data):
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(30, 64, 175)
        self.set_text_color(255, 255, 255)
        col_w = 180 // len(headers)
        for h in headers:
            self.cell(col_w, 8, h, border=1, fill=True, align='C')
        self.ln()
        self.set_font('Helvetica', '', 8)
        self.set_text_color(31, 41, 55)
        fill = False
        for row in data:
            if self.get_y() > 260:
                self.add_page()
            for i, cell in enumerate(row):
                self.cell(col_w, 7, str(cell)[:col_w // 3], border=1, fill=fill, align='C')
            self.ln()
            fill = not fill


def generate_report(report_type='daily'):
    today = datetime.now()
    if report_type == 'daily':
        title = f'Daily Traffic Report - {today.strftime("%B %d, %Y")}'
        date_from = today.date().isoformat()
        date_to = (today + timedelta(days=1)).isoformat()
    elif report_type == 'weekly':
        start = today - timedelta(days=today.weekday())
        title = f'Weekly Report - {start.strftime("%b %d")} to {today.strftime("%b %d, %Y")}'
        date_from = start.date().isoformat()
        date_to = (today + timedelta(days=1)).isoformat()
    else:
        start = today.replace(day=1)
        title = f'Monthly Report - {today.strftime("%B %Y")}'
        date_from = start.date().isoformat()
        date_to = (today + timedelta(days=1)).isoformat()

    stats = get_statistics()
    violations_by_type = get_violations_by_type()
    repeat_offenders = get_repeat_offenders(limit=10)
    hotspots = get_hotspots(min_count=1)
    daily_trend = get_violations_by_day(days=30)

    pdf = TrafficReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(0, 7, f'Generated: {today.strftime("%Y-%m-%d %H:%M")}', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(5)

    # Executive Summary
    pdf.section_title('Executive Summary')
    pdf.key_value('Total Violations', stats.get('total', 0))
    pdf.key_value('Unique Vehicles', stats.get('unique_vehicles', 0))
    pdf.key_value('High-Risk Offenders', stats.get('high_risk_offenders', 0))
    pdf.key_value('Report Period', f'{date_from} to {date_to}')
    pdf.ln(5)

    # Violation Breakdown
    pdf.section_title('Violation Breakdown')
    if violations_by_type:
        headers = ['Type', 'Count', '% of Total']
        total = stats.get('total', 1)
        data = [(v['type'].replace('_', ' ').title(), str(v['count']),
                 f'{v["count"] / total * 100:.1f}%') for v in violations_by_type]
        pdf.write_table(headers, data)
    pdf.ln(5)

    # Top Repeat Offenders
    if repeat_offenders:
        pdf.section_title('Top Repeat Offenders')
        headers = ['Vehicle', 'Total', 'Helmet', 'Overload', 'Risk Score', 'Status']
        data = [(o['vehicle_number'], str(o['total_violations']),
                 str(o.get('helmet_violations', 0)), str(o.get('overloading_violations', 0)),
                 str(o.get('risk_score', 0)), o.get('risk_status', 'LOW'))
                for o in repeat_offenders[:10]]
        pdf.write_table(headers, data)
        pdf.ln(5)

    # Hotspots
    if hotspots:
        pdf.section_title('Violation Hotspots')
        headers = ['Location', 'Type', 'Count', 'Risk Level']
        data = [(h['location_name'][:30], h['violation_type'].replace('_', ' ').title()[:20],
                 str(h['count']), h.get('risk_level', 'LOW')) for h in hotspots[:10]]
        pdf.write_table(headers, data)
        pdf.ln(5)

    risks = get_violations_by_type()
    pdf.section_title('Operational Recommendations')
    if risks:
        top_type = max(risks, key=lambda x: x['count'])['type'].replace('_', ' ').title()
        pdf.multi_cell(0, 6,
            f'Primary concern: {top_type} violations. '
            f'Recommended action: Increase enforcement at identified hotspots. '
            f'Deploy additional traffic officers during peak hours (8-10 AM, 5-7 PM). '
            f'High-risk repeat offenders require escalated monitoring and targeted enforcement drives.'
        )

    # Save
    os.makedirs(config.REPORT_DIR, exist_ok=True)
    filename = f'{report_type}_report_{today.strftime("%Y%m%d_%H%M%S")}.pdf'
    filepath = os.path.join(config.REPORT_DIR, filename)
    pdf.output(filepath)

    save_report(report_type, title,
                f'Total violations: {stats.get("total", 0)}, High-risk: {stats.get("high_risk_offenders", 0)}',
                filepath)

    return {'id': None, 'title': title, 'file_path': filepath, 'report_type': report_type}


def list_reports():
    from database.db import get_reports
    return get_reports(limit=20)
